language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database test;" -U postgres

env:
  - SECRET_KEY='CodeFellowsBlue' DEBUG='True' DB_NAME='test' DB_HOST='localhost'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python mercedes/manage.py migrate
  - coverage run mercedes/manage.py test mercedes

after_success:
  - coveralls

notifications:
  email: false