language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database test;" -U postgres

env:
  - SECRET_KEY='CodeFellowsBlue' DEBUG='True'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python askme/manage.py migrate
  - coverage run askme/manage.py test askme

after_success:
  - coveralls

notifications:
  email: false
